"""Repository quality checks for EmoSense."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PACKAGE_DIR = ROOT / "EmoSense"
SELF = Path(__file__).resolve()

REQUIRED_PATHS = [
    ROOT / "README.md",
    ROOT / ".gitattributes",
    ROOT / "requirements-dev.txt",
    ROOT / ".github" / "workflows" / "python-checks.yml",
    ROOT / "docs" / "ARCHITECTURE.md",
    ROOT / "docs" / "QA.md",
    PACKAGE_DIR / "README.md",
    PACKAGE_DIR / "analysis.py",
    PACKAGE_DIR / "analysis_components" / "pipeline.py",
    PACKAGE_DIR / "analysis_components" / "text_emotion.py",
    PACKAGE_DIR / "analysis_components" / "risk.py",
    PACKAGE_DIR / "tests" / "test_analysis.py",
    PACKAGE_DIR / "tests" / "test_diarization.py",
    PACKAGE_DIR / "tests" / "test_report_generator.py",
    PACKAGE_DIR / "tests" / "test_utils.py",
]

LINE_LIMITS = {
    PACKAGE_DIR / "analysis.py": 80,
    PACKAGE_DIR / "analysis_components" / "audio_features.py": 170,
    PACKAGE_DIR / "analysis_components" / "acoustic.py": 220,
    PACKAGE_DIR / "analysis_components" / "cnn.py": 90,
    PACKAGE_DIR / "analysis_components" / "pipeline.py": 220,
    PACKAGE_DIR / "analysis_components" / "risk.py": 220,
    PACKAGE_DIR / "analysis_components" / "smoothing.py": 90,
    PACKAGE_DIR / "analysis_components" / "text_emotion.py": 320,
    PACKAGE_DIR / "training_main.py": 430,
    PACKAGE_DIR / "verify_setup.py": 220,
}

TEXT_EXTENSIONS = {".md", ".py", ".txt", ".yml", ".yaml", ".json"}
IGNORED_DIRS = {".git", ".venv", "venv", "env", "__pycache__", ".pytest_cache", ".mypy_cache", ".ruff_cache"}
FORBIDDEN_TRACKED_DIRS = {"__pycache__", ".pytest_cache", ".venv", "venv", "env", "build", "dist"}
SOURCE_MARKERS = ["chat" + "gpt", "ai-" + "generated", "generated by " + "ai", "as an " + "ai"]
DRAFT_MARKERS = ["to" + "do", "fix" + "me", "place" + "holder", "dum" + "my"]
SUSPICIOUS_PATTERNS = [
    ("source marker", re.compile("|".join(SOURCE_MARKERS), re.IGNORECASE)),
    ("draft marker", re.compile(r"\b(" + "|".join(DRAFT_MARKERS) + r")\b", re.IGNORECASE)),
    ("oversized file marker", re.compile(r"\b" + "god" + "file" + r"\b", re.IGNORECASE)),
]


def tracked_files() -> list[Path]:
    try:
        result = subprocess.run(
            ["git", "ls-files"],
            cwd=ROOT,
            check=True,
            capture_output=True,
            text=True,
        )
    except (OSError, subprocess.CalledProcessError):
        return []

    return [ROOT / line.strip() for line in result.stdout.splitlines() if line.strip()]


def iter_text_files() -> list[Path]:
    files = []
    for path in ROOT.rglob("*"):
        if not path.is_file() or path.suffix.lower() not in TEXT_EXTENSIONS:
            continue
        if any(part in IGNORED_DIRS for part in path.relative_to(ROOT).parts):
            continue
        files.append(path)
    return files


def check_required_paths(errors: list[str]) -> None:
    for path in REQUIRED_PATHS:
        if not path.exists():
            errors.append(f"Missing required project file: {path.relative_to(ROOT)}")


def check_line_limits(errors: list[str]) -> None:
    for path, limit in LINE_LIMITS.items():
        if not path.exists():
            continue
        line_count = len(path.read_text(encoding="utf-8").splitlines())
        if line_count > limit:
            errors.append(f"{path.relative_to(ROOT)} has {line_count} lines; limit is {limit}")


def check_tracked_artifacts(errors: list[str]) -> None:
    for path in tracked_files():
        relative_parts = path.relative_to(ROOT).parts
        if any(part in FORBIDDEN_TRACKED_DIRS for part in relative_parts):
            errors.append(f"Generated artifact is tracked: {path.relative_to(ROOT)}")


def check_text_markers(errors: list[str]) -> None:
    for path in iter_text_files():
        if path.resolve() == SELF:
            continue

        text = path.read_text(encoding="utf-8")
        for label, pattern in SUSPICIOUS_PATTERNS:
            match = pattern.search(text)
            if match:
                errors.append(f"{label} in {path.relative_to(ROOT)}: {match.group(0)!r}")


def main() -> int:
    errors: list[str] = []
    check_required_paths(errors)
    check_line_limits(errors)
    check_tracked_artifacts(errors)
    check_text_markers(errors)

    if errors:
        print("Project quality checks failed:")
        for error in errors:
            print(f"- {error}")
        return 1

    print("Project quality checks passed.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
